### ISSUE TITLE
Observações por componente.

### ISSUE THREAD

**Issue by karolbelai** [BrunoAzzi/componentesweb#12]
Observações por componente, para o caso de haver componentes com especificações muito semelhantes entre si, tornando a visualização de suas divergências mais amplas.

**Comment by BrunoAzzi** [comment]
Pelo que eu entendi, você deseja um campo "Observação" no cadastro correto?

**Comment by karolbelai** [comment]
Sim, para itens como resistores que possuem mesmo valor, mesma referência, porém tolerâncias diferentes serial ideal um campo de ''Potência/Tolerância'' ao invés de ''Partnumber'' por exemplo.

**Comment by BrunoAzzi** [comment]
Tranquilo, estarei colocando esta funcionalidade na release de quinta feira, e mais futuramente creio que eu vá fazer uma forma nova de cadastro que pode vir por auxiliar bastante.

**Comment by BrunoAzzi** [comment]
Já implementado
